language: python
dist: xenial
os:
  - linux

python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'

cache:
  pip: true

install:
  - ./scripts/setup.sh

script:
  - ./scripts/test.sh
  - ./scripts/benchmark.sh
  - ./scripts/docs.sh
  - ./scripts/build.sh
